[package]
name = "zako3-audio-engine-protos"
version = "0.1.0"
edition = "2024"

[dependencies]
prost = "0.14.1"
tonic = "0.14.2"
tonic-prost = "0.14.2"

[build-dependencies]
tonic-build = "0.14.2"
prost-build = "0.14.1"
tonic-prost-build = "0.14.2"
