[package]
name = "zako3-audio-engine-infra"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.49.0", features = ["full"] }
zako3-audio-engine-core.workspace = true
async-trait = "0.1.89"
redis = { version = "0.27", features = ["tokio-comp"] }
serde_json = "1.0"
